config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :clothings do
    collection do
      get 'vetements', to: 'clothings#index_vetements'
      get 'sous-vetements', to: 'clothings#index_sous_vetements'
      get 'accessoires', to: 'clothings#index_accessoires'
    end
  end

  resources :bookings
  resources :orders
  resources :reviews
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :clothing
end

app/models/clothing.rb
class Clothing < ApplicationRecord
  has_many :bookings
  belongs_to :user
  has_one_attached :photo
  # has_many :orders
end

# belongs to order
# faire une migration pour enlever le order_id de la table clothing
# faire nouvelle migration pour ajouter un nouvel user dans la table clothing
# après la 2ème migration je decomente has many orders.

app/models/order.rb
class Order < ApplicationRecord
  has_many :orders_management
  has_many :clothings
end

app/models/orders_management.rb
class OrdersManagement < ApplicationRecord
  belongs_to :order
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :clothings
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :set_current_user
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: [:index, :index_vetements, :index_sous_vetements, :index_accessoires], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  private

  def set_current_user
    @user = current_user
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
end

app/controllers/clothings_controller.rb
class ClothingsController < ApplicationController
  # before_action :set_clothing, only: [:show]
  # before_action :authorize_admin, only: [:new, :create, :edit, :update, :destroy]
  # after_action :verify_policy_scoped, only: [:index, :index_vetements, :index_sous_vetements, :index_accessoires]
  def index
    @clothings = policy_scope(Clothing)
  end

  def index_vetements
    @clothings = Clothing.where(category: 'vetements')
    @clothing = Clothing.new
    # render :index_vetements
  end

  def index_sous_vetements
    @clothings = Clothing.where(category: 'sous-vetements')
    render :index_sous_vetements
  end

  def index_accessoires
    @clothings = Clothing.where(category: 'accessoires')
    render :index_accessoires
  end

  def show
    @clothing = Clothing.find(params[:id])
    authorize @clothing
  end

  def new
    @clothing = Clothing.new
  end

  def create
    # if current_user.nil?
    #   flash[:alert] = "You must be logged in to create a clothing."
    #   redirect_to login_path
    #   return
    # end
    # logger.debug "current_user: #{current_user.inspect}"
    @clothing = Clothing.new(clothing_params)
    authorize @clothing
    @clothing.user = current_user
    if @clothing.save
      redirect_to clothing_path(@clothing), notice: 'Clothing was successfully created.'
      #redirect_to vetements_clothings_path pour voir tous les vêtements que j'ai créé.
    else
      render :index_vetements, status: :unprocessable_entity
    end
  end

  def edit
    @clothing = Clothing.find(params[:id])
  end

  def update

    if @clothing.update(clothing_params)
      respond_to do |format|
        format.html { redirect_to clothing_path(@clothing), notice: 'Clothing was successfully updated.' }
        format.json { render json: { message: 'Clothing updated successfully' }, status: :ok }
      end
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: { errors: @clothing.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @clothing = Clothing.find(params[:id])
    authorize @clothing
    @clothing.destroy
    redirect_to clothings_path, notice: 'Clothing was successfully destroyed.'
  end

  private

  # def set_clothing
  #   @clothing = Clothing.find(params[:id])
  # end

  # def authorize_admin
  #   authorize Clothing, :admin?
  # end

  def clothing_params
    params.require(:clothing).permit(:name, :description, :price, :available_sizes, :category, :photo, :user_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show]

  def show
  end

  def edit
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clothings/index.html.erb
<div class="container-index">
  <div class="row">
    <div class="col">

      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1705120893666-d36e3156b07f?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
        <h1><strong>EmmaStitch</strong></h1>
        <p>Des Créations Uniques, Conçues Juste Pour Vous</p>
      </div>

      <div class="section-home index-clothings">
        <h2 class="custom-intro-section"> Collections </h2>
        <h3>Inclusif et Accessible, Adapté à Chaque Besoin</h3>
        <p>Paiement sécurisé et livraison offerte dès 79€ d'achat</p>
      </div>

      <div class="section-home index-clothings">
        <div class="parent-section">
          <div class="sub-section1">
            <h2> Vêtements </h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...</p>
            <div class="bouton-container">
              <%= link_to 'Découvrir', vetements_clothings_path, class: 'bouton-couture' %>
            </div>
          </div>

          <div class="sub-section2">
            <div class="carousel slide" id="carouselClothings1" data-bs-ride="carousel">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="https://images.unsplash.com/photo-1494228766058-1430438d10fc?q=80&w=2973&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="Image 1">
                </div>
                <div class="carousel-item">
                  <img src="https://images.unsplash.com/photo-1489007360682-2544382e1e73?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="Image 2">
                </div>
                <div class="carousel-item">
                  <img src="https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=3172&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="Image 3">
                </div>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselClothings1" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Précédent</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselClothings1" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Suivant</span>
              </button>
            </div>
          </div>
        </div>
      </div>

      <div class="section-home index-clothings">
        <div class="parent-section">
          <div class="sub-section2 img-left">
            <div class="carousel slide" id="carouselClothings2" data-bs-ride="carousel">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="https://images.unsplash.com/photo-1448582649076-3981753123b5?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="Image 1">
                </div>
                <div class="carousel-item">
                  <img src="https://images.unsplash.com/photo-1519144674309-fcb7fbc1a054?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="Image 2">
                </div>
                <div class="carousel-item">
                  <img src="https://images.unsplash.com/photo-1676303679145-8679f5ceeb16?q=80&w=2897&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="Image 3">
                </div>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselClothings2" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Précédent</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselClothings2" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Suivant</span>
              </button>
            </div>
          </div>

          <div class="sub-section1">
            <h2> Accessoires </h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit...</p>
            <div class="bouton-container">
              <%= link_to 'Découvrir', accessoires_clothings_path, class: 'bouton-couture' %>

            </div>
          </div>
        </div>
      </div>

      <div class="section-home index-clothings">
        <div class="parent-section">
          <div class="sub-section1">
            <h2>Sous-Vêtements</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit...</p>
            <div class="bouton-container">
              <%= link_to 'Découvrir', sous_vetements_clothings_path, class: 'bouton-couture' %>
            </div>
          </div>

          <div class="sub-section2">
            <div class="carousel slide" id="carouselClothings3" data-bs-ride="carousel">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="https://images.unsplash.com/photo-1506629371177-38dbb6e04a4e?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="Image 1">
                </div>
                <div class="carousel-item">
                  <img src="https://images.unsplash.com/photo-1566447172003-b861a3a44ae7?q=80&w=2974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="Image 2">
                </div>
                <div class="carousel-item">
                  <img src="https://images.unsplash.com/photo-1643539293760-0061e47e6828?q=80&w=3084&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="Image 3">
                </div>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselClothings3" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Précédent</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselClothings3" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Suivant</span>
              </button>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/clothings/index_vetements.html.erb
<div class="container-vetement">
  <!-- Bannière -->
  <div class="row">
    <div class="col-12">
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1705120893666-d36e3156b07f?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
        <h1><strong>EmmaStitch</strong></h1>
        <p>Des Créations Uniques, Conçues Juste Pour Vous</p>
      </div>
    </div>
  </div>

  <!-- Section Introduction -->
  <div class="row section-home index-clothings my-4">
    <div class="col-12 text-center">
      <h2 class="custom-intro-section">Vêtements</h2>
      <h3>Inclusif et Accessible, Adapté à Chaque Besoin</h3>
      <p>Paiement sécurisé et livraison offerte dès 79€ d'achat</p>
    </div>
  </div>

  <!-- Section Vêtements et Achat -->
  <div data-controller="card-vetements">
  <div class="row">

      <!-- Mosaïque des Vêtements -->
      <div class="section-vetements col-lg-8 col-md-7 col-12">
        <div class="mosaique-parent" data-card-vetements-target="imageContainer">
          <div class="mosaique-enfant">
            <!--<div class="mosaiquex1">
              <img src="https://images.unsplash.com/photo-1508808787069-421e7986016e?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
            </div>-->
            <div class="mosaiquex4">
              <div class="mosaiquex2">
                <!--<img src="https://images.unsplash.com/photo-1488409467762-3a18c42e36e2?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
                <img src="https://images.unsplash.com/photo-1562779198-651c8b760c00?q=80&w=2965&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">-->
              </div>
              <div class="mosaiquex2">
                <!--<img src="https://images.unsplash.com/photo-1569947494657-6837fd7cc18e?q=80&w=3051&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
                <img src="https://images.unsplash.com/photo-1619799382841-479db3616b91?q=80&w=3082&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">-->
              </div>
            </div>
          </div>
        </div>

        <div class="simple_form-add-clothing">
          <%= simple_form_for(@clothing) do |f| %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :available_sizes %>
            <%= f.input :category %>
            <%= f.input :price %>
            <%= f.input :photo, as: :file %>
            <%= f.submit %>
          <% end %>
        </div>
      </div>


      <!-- Description et Achat -->
      <div class="sous-section-achat col-lg-4 col-md-5 col-12">
        <div class="description-article">
          <% @clothings.each do |clothing| %>
            <h3><%= clothing.name %></h3>
            <p><%= clothing.description %></p>
            <p> <%= clothing.price %> <i class="fa-solid fa-euro-sign"></i></p>
          <% end %>
        </div>
        <div class="bouton-achat d-flex flex-column gap-2">
          <button class="bouton-couture">Acheter</button>
          <button class="bouton-couture">Message</button>
          <div class="icons">
            <i class="fa-solid fa-plus"></i>
            <i class="fa-solid fa-pencil"></i>
            <i class="fa-solid fa-trash-can"></i>
          </div>
        </div>

      </div>



      <!-- Section Couleurs -->
      <div class="row mt-5">
        <div class="col-12 text-center">
          <h3>Sélectionnez une couleur</h3>
          <div class="photo-couleur">
            <img src="https://images.unsplash.com/photo-1631089667980-7fe55b2abb9a?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Yellow" class="couleur-photo" data-action="click->card-vetements#changeColor" data-vetements-color="yellow">
            <img src="https://plus.unsplash.com/premium_photo-1674828601362-afb73c907ebe?q=80&w=2706&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Bleu" class="couleur-photo" data-action="click->card-vetements#changeColor" data-vetements-color="blue">
            <img src="https://images.unsplash.com/photo-1580133318324-f2f76d987dd8?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Vert" class="couleur-photo" data-action="click->card-vetements#changeColor" data-vetements-color="green">
            <img src="https://images.unsplash.com/photo-1582137808224-de22c65933c0?q=80&w=2788&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Rouge" class="couleur-photo" data-action="click->card-vetements#changeColor" data-vetements-color="red">
            <img src="https://images.unsplash.com/photo-1617055407123-3d7130c1f940?q=80&w=2835&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Rose" class="couleur-photo" data-action="click->card-vetements#changeColor" data-vetements-color="pink">
          </div>


        </div>
      </div>
    </div>
  </div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmmaStitch</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-home">
  <div class="row">
    <div class="col">

      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1705120893666-d36e3156b07f?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">

          <h1><strong>EmmaStitch</strong></h1>
          <p>Des Créations Uniques, Conçues Juste Pour Vous</p>

      </div>

      <div class="section-home">
        <h2> Couture sur mesure  </h2>
        <h3>Inclusif et Accessible, Adapté à Chaque Besoin</h3>

        <p> Paiement sécurisé et livraison offerte dès 79€ d'achat</p>
      </div>

      <div class="section-home">
        <div id="carousel-home" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="row">
                <div class="col-md-4">
                  <img src="https://images.unsplash.com/photo-1716541424893-734612ddcabb?q=80&w=2592&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="Image 1">
                </div>
                <div class="col-md-4">
                  <img src="https://images.unsplash.com/photo-1562157873-818bc0726f68?q=80&w=1854&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="Image 2">
                </div>
                <div class="col-md-4">
                  <img src="https://images.unsplash.com/photo-1716541424935-e28adbd63ca3?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="Image 3">
                </div>
              </div>
            </div>
            <div class="carousel-item">
              <div class="row">
                <div class="col-md-4">
                  <img src="https://images.unsplash.com/photo-1554568218-0f1715e72254?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="Image 4">
                </div>
                <div class="col-md-4">
                  <img src="https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="Image 5">
                </div>
                <div class="col-md-4">
                  <img src="https://images.unsplash.com/photo-1519211777646-3a7ccf759b64?q=80&w=1885&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="Image 6">
                </div>
              </div>
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Précédent</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Suivant</span>
          </button>
        </div>

      <div class="section-home">
        <div class="parent-section">
          <div class="sub-section1">
            <h2> Présentation </h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
              </p>
              <div class="bouton-container">
                <%= link_to "Découvrez nos Collections", clothings_path, class: "bouton-couture" %>

              </div>
          </div>
          <div class="sub-section2">
            <div class="img-section-home">
              <img src="https://ecn-neuropsy.com/wp-content/uploads/2023/12/Emmabisbisbis-e1703779369947.jpg" alt="">
            </div>
          </div>
        </div>

        <div class="parent-section">
          <div class="sub-section2 img-left">
            <div class="img-section-home">
              <img src="https://images.unsplash.com/photo-1658587165240-7d06b8f9ff04?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
            </div>
          </div>
          <div class="sub-section1">
            <h2> Nos valeurs </h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
              </p>
              <div class="bouton-container">
                <%= link_to "Découvrez nos Collections", clothings_path, class: "bouton-couture" %>
              </div>
          </div>
        </div>

        <div class="parent-section">
          <div class="sub-section1">
            <h2>La boutique </h2>
              <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
              </p>
              <div class="bouton-container">
                <%= link_to "Découvrez nos Collections", clothings_path, class: "bouton-couture" %>
              </div>
          </div>
          <div class="sub-section2">
            <div class="img-section-home">
              <img src="https://images.unsplash.com/photo-1524648829700-99c448a9e88d?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
            </div>
          </div>
        </div>
      </div>



      </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container container-profile-show">
  <p>Email: <%= @user.email %></p>
</div>